name: scrreens_second_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  go_router: ^13.2.0
  http: ^1.4.0
  intl_phone_field: ^3.2.0
  lottie: ^3.3.1
  material_design_icons_flutter: ^7.0.7296
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/Flags/
    - assets/lottie/
    - assets/svg/
    - assets/translations/
    - assets/icons/drawer/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
